openapi: 3.0.3
info:
  title: Система управления складом API
  description: API для системы управления складом с поддержкой товаров, продаж, запросов и управления пользователями
  version: 1.0.0
  contact:
    name: Система управления складом
    email: support@sklad.com

servers:
  - url: http://localhost/api
    description: Локальная разработка
  - url: https://your-domain.com/api
    description: Продакшн сервер

security:
  - bearerAuth: []

paths:
  # Аутентификация
  /auth/register:
    post:
      tags: [Аутентификация]
      summary: Регистрация пользователя
      description: Регистрация нового пользователя (только в dev окружении)
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password, password_confirmation]
              properties:
                name:
                  type: string
                  maxLength: 255
                username:
                  type: string
                  maxLength: 255
                email:
                  type: string
                  format: email
                  maxLength: 255
                password:
                  type: string
                  minLength: 8
                password_confirmation:
                  type: string
      responses:
        201:
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        403:
          description: Регистрация отключена в продакшн окружении
        422:
          description: Ошибки валидации

  /auth/login:
    post:
      tags: [Аутентификация]
      summary: Вход пользователя
      description: Аутентификация по email или username
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [login, password]
              properties:
                login:
                  type: string
                  description: Email или username
                password:
                  type: string
      responses:
        200:
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        401:
          description: Неверные учетные данные или аккаунт заблокирован

  /auth/logout:
    post:
      tags: [Аутентификация]
      summary: Выход пользователя
      responses:
        200:
          description: Успешно вышли из системы

  /auth/me:
    get:
      tags: [Аутентификация]
      summary: Информация о текущем пользователе
      responses:
        200:
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /auth/profile:
    put:
      tags: [Аутентификация]
      summary: Обновление профиля
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                username:
                  type: string
                  maxLength: 255
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                password_confirmation:
                  type: string
      responses:
        200:
          description: Профиль обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  # Товары
  /products:
    get:
      tags: [Товары]
      summary: Список товаров
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: Поиск по названию, описанию или производителю
        - name: warehouse_id
          in: query
          schema:
            type: integer
        - name: template_id
          in: query
          schema:
            type: integer
        - name: producer_id
          in: query
          schema:
            type: integer
        - name: in_stock
          in: query
          schema:
            type: boolean
        - name: low_stock
          in: query
          schema:
            type: boolean
        - name: active
          in: query
          schema:
            type: boolean
        - name: per_page
          in: query
          schema:
            type: integer
            default: 15
      responses:
        200:
          description: Список товаров
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  links:
                    $ref: '#/components/schemas/PaginationLinks'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'

    post:
      tags: [Товары]
      summary: Создание товара
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [product_template_id, warehouse_id, quantity]
              properties:
                product_template_id:
                  type: integer
                warehouse_id:
                  type: integer
                name:
                  type: string
                  maxLength: 255
                description:
                  type: string
                attributes:
                  type: object
                quantity:
                  type: number
                  minimum: 0
                transport_number:
                  type: string
                  maxLength: 255
                producer:
                  type: string
                  maxLength: 255
                producer_id:
                  type: integer
                arrival_date:
                  type: string
                  format: date
                is_active:
                  type: boolean
                status:
                  type: string
                  enum: [in_stock, in_transit, for_receipt]
                shipping_location:
                  type: string
                  maxLength: 255
                shipping_date:
                  type: string
                  format: date
                expected_arrival_date:
                  type: string
                  format: date
                notes:
                  type: string
                  maxLength: 1000
                document_path:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: Товар создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  product:
                    $ref: '#/components/schemas/Product'
        403:
          description: Доступ запрещен
        422:
          description: Ошибки валидации

  /products/{id}:
    get:
      tags: [Товары]
      summary: Получение товара по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Товар найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        403:
          description: Доступ запрещен
        404:
          description: Товар не найден

    put:
      tags: [Товары]
      summary: Обновление товара
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                description:
                  type: string
                attributes:
                  type: object
                quantity:
                  type: number
                  minimum: 0
                transport_number:
                  type: string
                  maxLength: 255
                producer:
                  type: string
                  maxLength: 255
                producer_id:
                  type: integer
                arrival_date:
                  type: string
                  format: date
                is_active:
                  type: boolean
                notes:
                  type: string
                  maxLength: 1000
                warehouse_id:
                  type: integer
      responses:
        200:
          description: Товар обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  product:
                    $ref: '#/components/schemas/Product'
        403:
          description: Доступ запрещен

    delete:
      tags: [Товары]
      summary: Удаление товара
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Товар удален
        403:
          description: Доступ запрещен

  /products/stats:
    get:
      tags: [Товары]
      summary: Статистика товаров
      responses:
        200:
          description: Статистика товаров
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_products:
                    type: integer
                  active_products:
                    type: integer
                  in_stock:
                    type: integer
                  low_stock:
                    type: integer
                  out_of_stock:
                    type: integer
                  total_quantity:
                    type: number
                  total_volume:
                    type: number

  /products/popular:
    get:
      tags: [Товары]
      summary: Популярные товары
      responses:
        200:
          description: Список популярных товаров
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /products/export:
    get:
      tags: [Товары]
      summary: Экспорт товаров
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: warehouse_id
          in: query
          schema:
            type: integer
        - name: template_id
          in: query
          schema:
            type: integer
        - name: producer_id
          in: query
          schema:
            type: integer
        - name: in_stock
          in: query
          schema:
            type: boolean
        - name: low_stock
          in: query
          schema:
            type: boolean
        - name: active
          in: query
          schema:
            type: boolean
      responses:
        200:
          description: Данные для экспорта
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                  total:
                    type: integer

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        middle_name:
          type: string
        phone:
          type: string
        role:
          type: string
          enum: [admin, operator, warehouse_worker, sales_manager]
        company_id:
          type: integer
        warehouse_id:
          type: integer
        is_blocked:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Product:
      type: object
      properties:
        id:
          type: integer
        product_template_id:
          type: integer
        warehouse_id:
          type: integer
        created_by:
          type: integer
        name:
          type: string
        description:
          type: string
        attributes:
          type: object
        calculated_volume:
          type: number
        quantity:
          type: number
        sold_quantity:
          type: integer
        transport_number:
          type: string
        producer_id:
          type: integer
        arrival_date:
          type: string
          format: date
        status:
          type: string
          enum: [in_stock, in_transit, for_receipt, correction]
        is_active:
          type: boolean
        shipping_location:
          type: string
        shipping_date:
          type: string
          format: date
        expected_arrival_date:
          type: string
          format: date
        actual_arrival_date:
          type: string
          format: date
        document_path:
          type: array
          items:
            type: string
        notes:
          type: string
        correction:
          type: string
        correction_status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        template:
          $ref: '#/components/schemas/ProductTemplate'
        warehouse:
          $ref: '#/components/schemas/Warehouse'
        creator:
          $ref: '#/components/schemas/User'
        producer:
          $ref: '#/components/schemas/Producer'

    ProductTemplate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        formula:
          type: string
        unit:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Warehouse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        company_id:
          type: integer
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Producer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        region:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Sale:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        warehouse_id:
          type: integer
        user_id:
          type: integer
        sale_number:
          type: string
        customer_name:
          type: string
        customer_phone:
          type: string
        customer_email:
          type: string
        customer_address:
          type: string
        quantity:
          type: integer
        unit_price:
          type: number
        total_price:
          type: number
        vat_rate:
          type: number
        vat_amount:
          type: number
        price_without_vat:
          type: number
        payment_method:
          type: string
          enum: [cash, card, bank_transfer, other]
        payment_status:
          type: string
          enum: [pending, paid, partially_paid, cancelled]
        notes:
          type: string
        sale_date:
          type: string
          format: date
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        legal_address:
          type: string
        postal_address:
          type: string
        phone_fax:
          type: string
        general_director:
          type: string
        email:
          type: string
        inn:
          type: string
        kpp:
          type: string
        ogrn:
          type: string
        bank:
          type: string
        account_number:
          type: string
        correspondent_account:
          type: string
        bik:
          type: string
        employees_count:
          type: integer
        warehouses_count:
          type: integer
        is_archived:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    PaginationLinks:
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        prev:
          type: string
        next:
          type: string

    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
        last_page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer

    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
